## Understanding DecomposeLinearExpressions()

In [28]:
from pydrake.all import (MathematicalProgram, DecomposeLinearExpressions, L2NormCost,
                         Binding, Cost)
import numpy as np

prog = MathematicalProgram()

x = prog.NewContinuousVariables(3)
exprs = [x[0]*5 - x[1], x[1]*2, x[2]*3 + x[0]]
A = DecomposeLinearExpressions(exprs, x)
print(A)

[[ 5. -1.  0.]
 [ 0.  2.  0.]
 [ 1.  0.  3.]]


In [23]:
b = np.zeros((A.shape[0], 1))
l2_norm_cost = L2NormCost(A, b)
for xi in x:
    cost = Binding[Cost](l2_norm_cost, [xi])
    prog.AddCost(cost)
print(prog.GetAllCosts())

SystemExit: Failure at bazel-out/darwin-opt/bin/tools/install/libdrake/_virtual_includes/drake_shared_library/drake/solvers/binding.h:31 in Binding(): condition 'c->num_vars() == v.rows() || c->num_vars() == Eigen::Dynamic' failed.

/Users/chewchiashaoyuan/Documents/Software/large_gcs/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3516: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [31]:
prog = MathematicalProgram()
x = prog.NewContinuousVariables(2)
l2_norm_cost = L2NormCost(np.array([1,-1]).reshape(1,2), np.array([0]).reshape(1,1))
print(l2_norm_cost)
cost = Binding[Cost](l2_norm_cost, np.array([x[0]]).reshape(1,1))
prog.AddCost(cost)
print(prog.GetAllCosts())

TypeError: AddCost(): incompatible function arguments. The following argument types are supported:
    1. (self: pydrake.solvers.MathematicalProgram, func: function, vars: numpy.ndarray[object[m, 1]], description: str = '') -> pydrake.solvers.Binding𝓣Cost𝓤
    2. (self: pydrake.solvers.MathematicalProgram, e: pydrake.symbolic.Expression) -> pydrake.solvers.Binding𝓣Cost𝓤
    3. (self: pydrake.solvers.MathematicalProgram, obj: pydrake.solvers.Cost, vars: numpy.ndarray[object[m, 1]]) -> pydrake.solvers.Binding𝓣Cost𝓤

Invoked with: <pydrake.solvers.MathematicalProgram object at 0x176096930>, <pydrake.solvers.Binding𝓣Cost𝓤 object at 0x104c7f130>